### ISSUE TITLE
Error with 2019.5.10

### ISSUE THREAD

**Issue by andrewsav-datacom** [DTW-DanWard/OctopusDeployUtilities#3]
Just upgraded to OD 2019.5.10 and `oduexport` produces:

```
Exporting data...
Exception calling "EndInvoke" with "1" argument(s): "The remote server returned an error: (404)
Not Found."
At line:13 char:25
+                         $Data = $job.InnerJob.EndInvoke($job.Handle)
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : RuntimeException
```

**Comment by andrewsav-datacom** [comment]
It appears that it's not the only issues with the current OD. They added a feature called "Spaces" so some relationships changed as they are now per space. It would be great if this app could be updated to support the latest Octopus Deploy version.

**Comment by andrewsav-datacom** [comment]
As for the source of the the first error, those two links do not exit (any more) [one](https://github.com/DTW-DanWard/OctopusDeployUtilities/blob/90973be0e7ad39df5768ccaedd1d13c7595c3af9/OctopusDeployUtilities/Source/Public/Export_OctoApi.ps1#L80), [two](https://github.com/DTW-DanWard/OctopusDeployUtilities/blob/90973be0e7ad39df5768ccaedd1d13c7595c3af9/OctopusDeployUtilities/Source/Public/Export_OctoApi.ps1#L92).

**Comment by DTW-DanWard** [comment]
Thanks for the specific API links; super helpful.  Will fix this in next day or two.

**Comment by andrewsav-datacom** [comment]
Consider adding logging these links in Verbose mode, otherwise, it's not easy to find which is which when they break. Thanks!

**Comment by andrewsav-datacom** [comment]
Hello, @DTW-DanWard I was wondering how this is going? Has this been fixed?

**Comment by DTW-DanWard** [comment]
Hey @andrewsav-datacom - I'm sorry for the delay, work has been incredibly busy.  Things should be quieting down by this weekend so I should have some time then.

**Comment by DTW-DanWard** [comment]
Hey @andrewsav-datacom - thanks for your patience, version 1.1.4 fixes those specific problems; just run: Update-Module OctopusDeployUtilities.  I also added some additional error handling that will make finding & fixing that particular issue much easier - handy with all these API updates. That said, I do need to go back through the Octo API with a fine-toothed comb to pick up all the changes from the past few months (spaces, etc.).  I hope to do that in the next few weeks, maybe this week.

Please let me know if you encounter any other bugs or specific API gaps and I'll get on them.  Unfortunately I've had no time at my full-time job to work on Octopus-related stuff the past few months but that should change in a month or two - at which time OctopusDeployUtilities will get more updates from me.

**Comment by andrewsav-bt** [comment]
Thanks a lot, appreciate the effort and the result.
